version: 2.1

orbs:
  android: circleci/android@2.3.0

jobs:
  unit_test_core:
    docker:
      - image: cimg/android:2023.08
    steps:
      - checkout
      - run:
          name: Give gradlew permission
          command: chmod +x ./gradlew
      - run:
          name: Run Core Unit Test
          command: ./gradlew :core:testDebugUnitTest
      - store_test_results:
          path: core/build/test-results
      - store_artifacts:
          path: core/build/reports/tests/testDebugUnitTest
          destination: core-unit-test-report

  coverage_core:
    docker:
      - image: cimg/android:2023.08
    steps:
      - checkout
      - run:
          name: Give gradlew permission
          command: chmod +x ./gradlew
      - run:
          name: Run JaCoCo Coverage Report for Core
          command: ./gradlew :core:jacocoTestReport
      - store_artifacts:
          path: core/build/reports/jacoco/jacocoTestReport/html
          destination: core-code-coverage

workflows:
  core_ci:
    jobs:
      - unit_test_core
      - coverage_core:
          requires:
            - unit_test_core
